// apps/web/src/app/orders/page.tsx
'use client';

import React, { useEffect, useState } from 'react';
import Link from 'next/link';
import { ProtectedRoute } from '../../components/ProtectedRoute';
import { ordersApi } from '../../lib/api/orders';
import { Order } from '../../types/order';
import { Alert } from '../../components/Alert';

function OrdersContent() {
  const [orders, setOrders] = useState<Order[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  useEffect(() => {
    fetchOrders();
  }, []);

  const fetchOrders = async () => {
    setIsLoading(true);
    setErrorMessage(null);
    try {
      const data = await ordersApi.getMyOrders();
      setOrders(data);
    } catch (err: any) {
      setErrorMessage(err.message || 'Unable to retrieve your orders from the Orders Service.');
    } finally {
      setIsLoading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    const s = status.toUpperCase();
    if (s === 'COMPLETED') {
      return <span className="badge badge-completed">✓ Completed</span>;
    }
    if (s === 'PROCESSING') {
      return <span className="badge badge-processing">⚙️ Processing</span>;
    }
    return <span className="badge badge-pending">⏳ Pending</span>;
  };

  return (
    <div>
      <div className="card">
        <div className="card-header">
          <div>
            <h1>My Orders</h1>
            <p className="subtitle">
              Your personal order history retrieved securely from the Spring Boot Orders Service.
            </p>
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button
              type="button"
              className="btn btn-outline btn-sm"
              onClick={fetchOrders}
              disabled={isLoading}
            >
              🔄 Refresh Orders
            </button>
            <Link href="/products" className="btn btn-primary btn-sm">
              + New Order
            </Link>
          </div>
        </div>

        {errorMessage && (
          <Alert
            type="error"
            title="Orders Error"
            message={errorMessage}
            onClose={() => setErrorMessage(null)}
          />
        )}

        {isLoading ? (
          <div className="loading-state">
            <div className="spinner"></div>
            <p>Loading your orders...</p>
          </div>
        ) : orders.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">🛒</div>
            <h3>No Orders Found</h3>
            <p className="subtitle">You have not placed any orders yet.</p>
            <Link href="/products" className="btn btn-primary" style={{ marginTop: '0.5rem' }}>
              Browse Products to Place an Order
            </Link>
          </div>
        ) : (
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Order ID</th>
                  <th>Product</th>
                  <th>Unit Price</th>
                  <th>Quantity</th>
                  <th>Total</th>
                  <th>Status</th>
                  <th>Placed At</th>
                </tr>
              </thead>
              <tbody>
                {orders.map((order) => {
                  const price = order.product?.price ? Number(order.product.price) : 0;
                  const total = price * order.quantity;
                  const formattedDate = order.createdAt
                    ? new Date(order.createdAt).toLocaleString()
                    : 'N/A';

                  return (
                    <tr key={order.id}>
                      <td>
                        <strong>#{order.id}</strong>
                      </td>
                      <td>{order.product?.name || 'Unknown Item'}</td>
                      <td>${price.toFixed(2)}</td>
                      <td>{order.quantity}</td>
                      <td>
                        <strong style={{ color: 'var(--accent-cyan)' }}>${total.toFixed(2)}</strong>
                      </td>
                      <td>{getStatusBadge(order.status)}</td>
                      <td style={{ color: 'var(--text-muted)', fontSize: '0.8rem' }}>{formattedDate}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}

export default function OrdersPage() {
  return (
    <ProtectedRoute>
      <OrdersContent />
    </ProtectedRoute>
  );
}

// apps/dashboard/src/app/features/orders/orders.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { OrdersApiService } from '../../core/api/orders-api.service';
import { Order, OrderStatus } from '../../core/models/order.model';

@Component({
  selector: 'app-orders',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './orders.component.html',
  styleUrls: [],
})
export class OrdersComponent implements OnInit {
  private ordersApi = inject(OrdersApiService);

  orders: Order[] = [];
  selectedStatuses: Record<number, OrderStatus> = {};
  updatingOrderId: number | null = null;

  activeFilter: 'ALL' | OrderStatus = 'ALL';
  isLoading = true;
  errorMessage: string | null = null;
  successMessage: string | null = null;

  readonly availableStatuses: OrderStatus[] = ['PENDING', 'PROCESSING', 'COMPLETED'];

  ngOnInit(): void {
    this.fetchOrders();
  }

  fetchOrders(): void {
    this.isLoading = true;
    this.errorMessage = null;

    this.ordersApi.getAllOrders().subscribe({
      next: (data) => {
        this.orders = data;
        this.selectedStatuses = {};
        data.forEach((o) => {
          this.selectedStatuses[o.id] = o.status;
        });
        this.isLoading = false;
      },
      error: (err) => {
        this.isLoading = false;
        this.errorMessage =
          err.error?.message ||
          err.error?.detail ||
          'Failed to retrieve orders from Orders Service.';
      },
    });
  }

  get filteredOrders(): Order[] {
    if (this.activeFilter === 'ALL') {
      return this.orders;
    }
    return this.orders.filter((o) => o.status === this.activeFilter);
  }

  setFilter(filter: 'ALL' | OrderStatus): void {
    this.activeFilter = filter;
  }

  onStatusChange(orderId: number, newStatus: OrderStatus): void {
    this.selectedStatuses[orderId] = newStatus;
  }

  updateStatus(order: Order): void {
    const targetStatus = this.selectedStatuses[order.id];
    if (!targetStatus || targetStatus === order.status) {
      return;
    }

    this.updatingOrderId = order.id;
    this.errorMessage = null;
    this.successMessage = null;

    this.ordersApi.updateOrderStatus(order.id, targetStatus).subscribe({
      next: (updated) => {
        this.updatingOrderId = null;
        this.orders = this.orders.map((o) => (o.id === updated.id ? updated : o));
        this.selectedStatuses[updated.id] = updated.status;
        this.successMessage = `Order #${updated.id} status successfully transitioned to ${updated.status}.`;
      },
      error: (err) => {
        this.updatingOrderId = null;
        this.errorMessage =
          err.error?.message ||
          err.error?.detail ||
          `Failed to update status for Order #${order.id}.`;
      },
    });
  }
}

<div class="orders-page">
  <div class="card">
    <div class="card-header">
      <div>
        <h1>Orders Management</h1>
        <p class="subtitle">
          Administrative inspection and status lifecycle transitions for all customer orders.
        </p>
      </div>
      <button
        type="button"
        class="btn btn-outline btn-sm"
        (click)="fetchOrders()"
        [disabled]="isLoading"
      >
        🔄 Refresh Orders
      </button>
    </div>

    @if (errorMessage) {
      <div class="alert alert-error">
        <span>{{ errorMessage }}</span>
      </div>
    }

    @if (successMessage) {
      <div class="alert alert-success">
        <span>{{ successMessage }}</span>
      </div>
    }

    <!-- Status Filter Tabs -->
    <div class="tab-row">
      <button
        type="button"
        class="tab-btn"
        [class.active]="activeFilter === 'ALL'"
        (click)="setFilter('ALL')"
      >
        All Orders ({{ orders.length }})
      </button>
      <button
        type="button"
        class="tab-btn"
        [class.active]="activeFilter === 'PENDING'"
        (click)="setFilter('PENDING')"
      >
        ⏳ Pending
      </button>
      <button
        type="button"
        class="tab-btn"
        [class.active]="activeFilter === 'PROCESSING'"
        (click)="setFilter('PROCESSING')"
      >
        ⚙️ Processing
      </button>
      <button
        type="button"
        class="tab-btn"
        [class.active]="activeFilter === 'COMPLETED'"
        (click)="setFilter('COMPLETED')"
      >
        ✓ Completed
      </button>
    </div>

    @if (isLoading) {
      <div class="loading-state">
        <div class="spinner"></div>
        <p>Loading system orders from Orders Service...</p>
      </div>
    } @else if (filteredOrders.length === 0) {
      <div class="empty-state">
        <div class="empty-icon">📦</div>
        <h3>No Orders Found</h3>
        <p class="subtitle">No orders match the selected filter category.</p>
      </div>
    } @else {
      <div class="table-container">
        <table class="data-table">
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Customer ID</th>
              <th>Product Details</th>
              <th>Quantity</th>
              <th>Total Amount</th>
              <th>Current Status</th>
              <th>Order Date</th>
              <th>Admin Action</th>
            </tr>
          </thead>
          <tbody>
            @for (order of filteredOrders; track order.id) {
              <tr>
                <td>
                  <strong>#{{ order.id }}</strong>
                </td>
                <td>
                  <span class="user-tag">User #{{ order.userId }}</span>
                </td>
                <td>
                  <div>
                    <strong>{{ order.product.name }}</strong>
                  </div>
                  <div style="font-size: 0.75rem; color: var(--text-muted)">
                    Unit Price: ${{ (order.product.price || 0).toFixed(2) }}
                  </div>
                </td>
                <td>{{ order.quantity }}</td>
                <td>
                  <strong style="color: var(--accent-cyan)">
                    ${{ ((order.product.price || 0) * order.quantity).toFixed(2) }}
                  </strong>
                </td>
                <td>
                  @if (order.status === 'COMPLETED') {
                    <span class="badge badge-completed">✓ Completed</span>
                  } @else if (order.status === 'PROCESSING') {
                    <span class="badge badge-processing">⚙️ Processing</span>
                  } @else {
                    <span class="badge badge-pending">⏳ Pending</span>
                  }
                </td>
                <td style="color: var(--text-muted); font-size: 0.8rem">
                  {{ order.createdAt | date: 'medium' }}
                </td>
                <td>
                  <div class="action-cell">
                    <select
                      class="status-select"
                      [ngModel]="selectedStatuses[order.id]"
                      (ngModelChange)="onStatusChange(order.id, $event)"
                      [disabled]="updatingOrderId === order.id"
                      aria-label="Select order status"
                    >
                      @for (st of availableStatuses; track st) {
                        <option [value]="st">{{ st }}</option>
                      }
                    </select>

                    <button
                      type="button"
                      class="btn btn-primary btn-sm"
                      (click)="updateStatus(order)"
                      [disabled]="
                        updatingOrderId === order.id || selectedStatuses[order.id] === order.status
                      "
                    >
                      @if (updatingOrderId === order.id) {
                        Saving...
                      } @else {
                        Update
                      }
                    </button>
                  </div>
                </td>
              </tr>
            }
          </tbody>
        </table>
      </div>
    }
  </div>
</div>
