// apps/web/src/app/login/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { useAuth } from '../../lib/auth/use-auth';
import { Alert } from '../../components/Alert';
import { ApiError } from '../../lib/api/client';

export default function LoginPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { login, isAuthenticated } = useAuth();

  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [infoMessage, setInfoMessage] = useState<string | null>(null);

  const redirectUrl = searchParams.get('redirect') || '/products';
  const isRegistered = searchParams.get('registered') === 'true';

  useEffect(() => {
    if (isRegistered) {
      setInfoMessage('Account created successfully! Please log in with your credentials.');
    }
  }, [isRegistered]);

  useEffect(() => {
    if (isAuthenticated) {
      router.push(redirectUrl);
    }
  }, [isAuthenticated, router, redirectUrl]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage(null);

    if (!username.trim() || !password) {
      setErrorMessage('Please enter both your username and password.');
      return;
    }

    setIsLoading(true);
    try {
      await login({ username: username.trim(), password });
      router.push(redirectUrl);
    } catch (err: any) {
      if (err instanceof ApiError) {
        setErrorMessage(err.message);
      } else {
        setErrorMessage(err.message || 'Invalid credentials or unable to reach Identity Service.');
      }
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '440px', margin: '0 auto' }}>
      <div className="card">
        <h1>Sign In</h1>
        <p className="subtitle">
          Authenticate with the Django Identity Service using your credentials.
        </p>

        {infoMessage && (
          <Alert
            type="success"
            message={infoMessage}
            onClose={() => setInfoMessage(null)}
          />
        )}

        {errorMessage && (
          <Alert
            type="error"
            title="Authentication Error"
            message={errorMessage}
            onClose={() => setErrorMessage(null)}
          />
        )}

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label" htmlFor="username">Username</label>
            <input
              id="username"
              type="text"
              className="form-input"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              placeholder="Username"
              autoComplete="username"
              required
              disabled={isLoading}
            />
          </div>

          <div className="form-group">
            <label className="form-label" htmlFor="password">Password</label>
            <input
              id="password"
              type="password"
              className="form-input"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Password"
              autoComplete="current-password"
              required
              disabled={isLoading}
            />
          </div>

          <button
            type="submit"
            className="btn btn-primary"
            style={{ width: '100%', marginTop: '0.5rem' }}
            disabled={isLoading}
          >
            {isLoading ? 'Signing In...' : 'Log In'}
          </button>
        </form>

        <div style={{ marginTop: '1.5rem', textAlign: 'center', fontSize: '0.875rem', color: 'var(--text-secondary)' }}>
          Don't have an account?{' '}
          <Link href="/register" style={{ color: 'var(--accent-cyan)', fontWeight: 600, textDecoration: 'none' }}>
            Register here &rarr;
          </Link>
        </div>
      </div>
    </div>
  );
}

// apps/dashboard/src/app/features/login/login.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, ActivatedRoute, RouterModule } from '@angular/router';
import { AuthService } from '../../core/auth/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: []
})
export class LoginComponent implements OnInit {
  private authService = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  username = '';
  password = '';
  isLoading = false;
  errorMessage: string | null = null;
  returnUrl = '/dashboard';

  ngOnInit(): void {
    const errorParam = this.route.snapshot.queryParamMap.get('error');
    if (errorParam === 'forbidden') {
      this.errorMessage = 'Access denied: Your account does not have administrator privileges.';
    }

    const returnUrlParam = this.route.snapshot.queryParamMap.get('returnUrl');
    if (returnUrlParam) {
      this.returnUrl = returnUrlParam;
    }

    if (this.authService.isAdmin()) {
      this.router.navigate([this.returnUrl]);
    }
  }

  onSubmit(): void {
    this.errorMessage = null;

    if (!this.username.trim() || !this.password) {
      this.errorMessage = 'Please enter both username and password.';
      return;
    }

    this.isLoading = true;
    this.authService.login({
      username: this.username.trim(),
      password: this.password
    }).subscribe({
      next: () => {
        this.isLoading = false;
        if (this.authService.isAdmin()) {
          this.router.navigate([this.returnUrl]);
        } else {
          this.authService.logout();
          this.errorMessage = 'Access denied: Authenticated user does not possess administrative role (admin).';
        }
      },
      error: (err) => {
        this.isLoading = false;
        if (err.status === 401) {
          this.errorMessage = 'Invalid username or password.';
        } else if (err.status === 0) {
          this.errorMessage = 'Unable to reach Django Identity Service on port 8001. Please verify the service is running.';
        } else {
          this.errorMessage = err.error?.detail || err.error?.message || 'An error occurred during authentication.';
        }
      }
    });
  }
}

<div class="login-container">
  <div class="card login-card">
    <div class="login-header">
      <div class="brand-badge" style="margin-bottom: 0.5rem;">CONTROL PLANE</div>
      <h1>Administrator Sign In</h1>
      <p class="subtitle">
        Enter your administrative credentials to access the DevSecOps Operations Dashboard.
      </p>
    </div>

    @if (errorMessage) {
      <div class="alert alert-error">
        <span>{{ errorMessage }}</span>
      </div>
    }

    <form (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label class="form-label" for="username">Username</label>
        <input
          id="username"
          type="text"
          name="username"
          class="form-input"
          [(ngModel)]="username"
          placeholder="Admin username"
          autocomplete="username"
          required
          [disabled]="isLoading"
        />
      </div>

      <div class="form-group">
        <label class="form-label" for="password">Password</label>
        <input
          id="password"
          type="password"
          name="password"
          class="form-input"
          [(ngModel)]="password"
          placeholder="Admin password"
          autocomplete="current-password"
          required
          [disabled]="isLoading"
        />
      </div>

      <button
        type="submit"
        class="btn btn-primary"
        style="width: 100%; margin-top: 0.5rem;"
        [disabled]="isLoading"
      >
        @if (isLoading) {
          Authenticating...
        } @else {
          Sign In to Dashboard &rarr;
        }
      </button>
    </form>

    <div class="login-footer">
      <small style="color: var(--text-muted);">
        🔒 Authentication verified with Django Identity Service via stateless JWT.
      </small>
    </div>
  </div>
</div>
